global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'proxmox'
    static_configs:
      - targets: ['<192.168.127.134>:<8006>']
    metrics_path: '/api2/json'
    params:
      node: ['<locale>']
    bearer_token: '<faf0b3f2-8df5-48ec-b726-6fadc60aa5d1>'
    scheme: https
    insecure_skip_verify: true
